// Note to LLM: do not edit this file, just use the exposed interface

import { ref } from 'vue';
import { defineStore } from 'pinia';
import type * as CRUDL from '../crudl-client';

function generateStorageKey(type: string, id: string): string {
  return `${type}#${id}`;
}

export const useLocalCrudlStore = defineStore('localCrudl', () => {
  const items = ref(new Map<string, CRUDL.Item>());

  async function createItem(item: Partial<CRUDL.Item>): Promise<CRUDL.Item> {
      const itemId = item.id || crypto.randomUUID();
      const itemType = item.type;
      const itemParentType = item.parentType || 'USER';
      const itemParentId = item.parentId || 'USER_ID'; // Simulated single user for local implementation

      const now = new Date().toISOString();
      const meta: CRUDL.ItemMeta = {
        createdAt: now,
        updatedAt: now,
        version: 1,
      };

      const newItem: CRUDL.Item = {
        type: itemType,
        id: itemId,
        parentType: itemParentType,
        parentId: itemParentId,
        data: item?.data || {},
        meta,
        user: 'USER_ID', // Associate with the simulated single user
      };

      const storageKey = generateStorageKey(itemType, itemId);
      if (items.value.has(storageKey)) {
        throw new Error(`Item with key ${storageKey} already exists`);
      }

      items.value.set(storageKey, newItem);
      return newItem;
    }

    async function readItem(type: string, id: string): Promise<CRUDL.Item> {
      const storageKey = generateStorageKey(type, id);
      const item = items.value.get(storageKey);
      if (!item) throw new Error(`Item with key ${storageKey} not found`);
      else return item;
    }

    async function upsertItem(
      type: string,
      id: string,
      item: Partial<CRUDL.Item>
    ): Promise<CRUDL.Item> {
      const storageKey = generateStorageKey(type, id);
      const existingItem = items.value.get(storageKey);
      if (!existingItem) throw new Error(`Item with key ${storageKey} not found`);

      const currentMeta = existingItem.meta || { createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: 0 };

      const newMeta: CRUDL.ItemMeta = {
        ...currentMeta,
        updatedAt: new Date().toISOString(),
        version: currentMeta.version + 1,
      };

      // Field-level upsert: override only the fields present on the partial item.
      // `id`/`type` are part of the storage key and are intentionally not
      // mutated, even if present on the partial item.
      const updatedItem: CRUDL.Item = {
        ...existingItem,
        ...(item.type !== undefined && { type: item.type }),
        ...(item.parentType !== undefined && { parentType: item.parentType }),
        ...(item.parentId !== undefined && { parentId: item.parentId }),
        ...(item.data !== undefined && { data: item.data }),
        ...(item.user !== undefined && { user: item.user }),
        meta: newMeta,
      };

      items.value.set(storageKey, updatedItem);
      return updatedItem;
    }

    async function updateItemData(
      type: string,
      id: string,
      dataUpdates: CRUDL.ItemData
    ): Promise<CRUDL.Item> {
      const storageKey = generateStorageKey(type, id);
      const existingItem = items.value.get(storageKey);
      if (!existingItem) throw new Error(`Item with key ${storageKey} not found`);

      const currentMeta = existingItem.meta || { createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: 0 };

      const newMeta: CRUDL.ItemMeta = {
        ...currentMeta,
        updatedAt: new Date().toISOString(),
        version: currentMeta.version + 1,
      };

      // Merge the data updates into the existing data.
      const updatedItem: CRUDL.Item = {
        ...existingItem,
        data: { ...(existingItem.data || {}), ...dataUpdates },
        meta: newMeta,
      };

      items.value.set(storageKey, updatedItem);
      return updatedItem;
    }

    async function deleteItem(type: string, id: string): Promise<void> {
      const storageKey = generateStorageKey(type, id);
      if (!items.value.has(storageKey)) {
        throw new Error(`Item with key ${storageKey} not found for delete`);
      }
      items.value.delete(storageKey);
      return Promise.resolve();
    }

    async function listChildItems(
      parentType: string,
      parentId: string,
      childType='all',
      options?: CRUDL.QueryOptions
    ): Promise<CRUDL.QueryResponse> {
      const limit = options?.limit || 50;
      const startIndex = options?.nextPage ? parseInt(options.nextPage, 10) : 0;

      const allMatchingChildren: CRUDL.Item[] = [];
      for (const item of items.value.values()) { //TODO confirm shape of items and why we are using .values() here
        if (item.parentType === parentType && item.parentId === parentId) {
          if (childType && childType !== 'all' && item.type !== childType) {
            continue;
          }
          allMatchingChildren.push(item);
        }
      }

      const paginatedItems = allMatchingChildren.slice(startIndex, startIndex + limit);
      let newNextPage: string | undefined = undefined;

      if (startIndex + limit < allMatchingChildren.length) {
        newNextPage = (startIndex + limit).toString();
      }

      return { items: paginatedItems, nextPage: newNextPage };
    }

    async function listUserItems(
      type='all',
      options?: CRUDL.QueryOptions
    ): Promise<CRUDL.QueryResponse> {
      const limit = options?.limit || 50;
      const startIndex = options?.nextPage ? parseInt(options.nextPage, 0) : 0;

      // Get all items from the store
      let allItemsInStore: CRUDL.Item[] = Array.from(items.value.values());

      let filteredItems: CRUDL.Item[];
      if (type && type !== 'all') {
        // Filter by type if provided and not 'all'
        filteredItems = allItemsInStore.filter(item => item.type === type);
      } else {
        // Otherwise, use all items (no type filter or type is 'all')
        filteredItems = allItemsInStore;
      }

      const paginatedItems = filteredItems.slice(startIndex, startIndex + limit);
      const newNextPage = (startIndex + limit < filteredItems.length) ? (startIndex + limit).toString() : undefined;

      // Using Promise.resolve as per example, though direct return of the object is also fine in async function
      return Promise.resolve({ items: paginatedItems, nextPage: newNextPage });
    }

    return {
      items,
      createItem,
      readItem,
      upsertItem,
      updateItemData,
      deleteItem,
      listChildItems,
      listUserItems
    }
  },
  {
    persist: {
      key: 'crudlLocal',
      storage: localStorage,
      serializer: {
        serialize: (state) => {
          return JSON.stringify(Array.from(state.items.entries()))
        },
        deserialize: (storedValue) => {
          try {
            const entries = JSON.parse(storedValue)
            return { items: new Map(entries) }
          } catch {
            return { items: new Map() }
          }
        }
      }
    },
  }
);
