// Note to LLM: do not edit this file, just use the exposed interface

import { useLocalCrudlStore } from '@/stores/crudlLocal';

export interface ItemMeta {
  createdAt: string;
  updatedAt: string;
  version: number;
}

export interface Item {
  type: string;
  id?: string;
  parentType?: string;
  parentId?: string;
  data?: Record<string, any>;
  meta?: ItemMeta;
  user?: string; // Cognito user sub
}

export interface QueryResponse {
  items: Item[];
  nextPage?: string;
}

/* --- */

export async function createItem(
  item: Partial<Item>
): Promise<Item> {
  const store = useLocalCrudlStore();
  return store.createItem(item);
}

export async function readItem(
  type: string,
  id: string
): Promise<Item> {
  const store = useLocalCrudlStore();
  return store.readItem(type, id);
}

export async function updateItem(
  type: string,
  id: string,
  data: Record<string, any>,
  options?: { merge?: boolean }
): Promise<Item> {
  const store = useLocalCrudlStore();
  return store.updateItem(type, id, data, options);
}

export async function deleteItem(
  type: string,
  id: string
): Promise<void> {
  const store = useLocalCrudlStore();
  return store.deleteItem(type, id);
}

export async function listChildren(
  parentType: string,
  parentId: string,
  childType?: string,
  options?: { limit?: number; nextPage?: string }
): Promise<QueryResponse> {
  const store = useLocalCrudlStore();
  return store.listChildren(parentType, parentId, childType, options);
}

export async function listUserItems(
  type?: string,
  options?: { limit?: number; nextPage?: string }
): Promise<QueryResponse> {
  const store = useLocalCrudlStore();
  return store.listUserItems(type, options);
}
